# Generated by Django 4.2.7 on 2024-01-05 05:39

from django.db import migrations, models
import todoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created',
            field=models.CharField(default=todoapp.models.getmonthday, max_length=50),
        ),
    ]
