# Generated by Django 4.2.7 on 2024-01-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todolist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
